### ISSUE TITLE
Removal of data

### ISSUE THREAD

**Issue by inlovesushi** [camas/reddit-search#16]
Someone has recently started stalking my main reddit account. Is there any way you can remove my data? I have deleted my main account, but he seems like the sort of person who would go out of his way to find an archive like this one.

**Comment by camas** [comment]
See [here](https://www.reddit.com/r/pushshift/comments/kmuiy4/data_deletion_request_megathread/) if you want pushshift (the API this app uses) to delete anything. The response time doesn't seem to be great though.

**Comment by justaoneoffthing** [comment]
> Someone has recently started stalking my main reddit account. Is there any way you can remove my data? I have deleted my main account, but he seems like the sort of person who would go out of his way to find an archive like this one.

Has your problem been resolved yet? I've tried contacting both devs but have yet to get a reply. Was wondering how long they took to respond your request? Thanks
