### ISSUE TITLE
RFCs: Ability to see deleted posts by user/data deletion requests

### ISSUE THREAD

**Issue by plebbituser** [camas/reddit-search#23]
This is really two RFCs packed into one issue for easier tracking and management. 

**RFC 1: See deleted posts by user**

archivesort.org/redditfinder along with github.coddit.xyz has the ability to filter out all deleted posts by user. Many people using the tool would like to see only the deleted posts of a user. This RFC would investigate how we could somehow integrate that ability into Camas Search. There are two options really:

- Integrate archivesort.org's api into Camas for this feature. This is not the right approach in my opinion due to the the relative age and instability of the platform plus the fact its still in alpha and flushing out api endpoints. 

- Make requests to Pushshift's API and then make requests to the Reddit API and then see what was deleted. This is what Removeddit does, and I think this is the right approach as of right now. It seems like github.coddit.xyz does this already.

A tricky problem is figuring out how to handle pagination - in order to check all deleted posts we would need to gather all of the user's posts through Pushshift and then query the Reddit API.

I would like to get working on this, but I want to know what direction I should take.

**RFC 2: Data deletion** 

An increasing group of people would like to have their posts deleted from Pushshift and thus Camas Search. The owner has stated that they are fully supportive of data deletions (https://twitter.com/jasonbaumgartne/status/1400104801510301704), but maybe an alternative approach is needed since he doesn't seem to be responsive. There are 3 viable options really:

1. Don't do anything about it. I think this is the best option by far. There are many archives other than Pushshift and many other Pushshift-specific search sites, and while Camas seems to be the biggest one, it would only be putting a "bandaid" on a very big wound. 

2. Have a list of usernames in the repo that when their name is searched, nothing will come up. However this will cause a very large Stristand effect since people will rush to archive and store all those usernames. The situation could be better if the usernames were hashed making retrieving the original usernames not trivial.

3. Have an external server that Camas pings to see if the author has marked data for deletion. The server would presumably be in control of Camas or a trusted contributor, and the usernames on that server would be kept private. However that is another extra request and performance testing would be required.

If no one comments on this RFC I would assume 1 is the best option to take. Like I said before, options 2 and 3 sound like very inefficient and essentially useless solutions to the problem, as the problem is with Pushshift, not the tool, but it's good to get opinions on this.

@camas @pushshift @godthreads @justaoneoffthing

**Comment by camas** [comment]
Regarding 1, I originally made this because there was nothing else. Thank you for mentioning Coddit as it seems to do everything this does and more, the only downside I can see is that it isn't open source? While Coddit and the like exist I have no plans to repeat their work but good luck if you decide to try that yourself.

For RFC 2 hashing usernames to hide results could possibly work but would mean taking on extra responsibilities for a project I haven't spent too much time on since originally making, and would also mean degrading results compared to other sites that use the same API. Essentially what you say in 1 and your last comments.
